// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6R4vUtevig_H8d0E0QAyXQidvHNy7Ao',
    appId: '1:425854454704:web:5459a263532448f9282475',
    messagingSenderId: '425854454704',
    projectId: 'schedulingfyp-e383b',
    authDomain: 'schedulingfyp-e383b.firebaseapp.com',
    storageBucket: 'schedulingfyp-e383b.firebasestorage.app',
    measurementId: 'G-WSCX1V77NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkP_4q0luHfgfPRilj_WanhICqKybbE0',
    appId: '1:425854454704:android:49948a92af24f188282475',
    messagingSenderId: '425854454704',
    projectId: 'schedulingfyp-e383b',
    storageBucket: 'schedulingfyp-e383b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvR7_YF9v0K24v-r39SpMkWi6UDnL3Ozo',
    appId: '1:425854454704:ios:481b483049dd5273282475',
    messagingSenderId: '425854454704',
    projectId: 'schedulingfyp-e383b',
    storageBucket: 'schedulingfyp-e383b.firebasestorage.app',
    iosClientId: '425854454704-dl4rf2r93gj462r7pprhbg37u2dglt91.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduling',
  );

}